### PR TITLE
patches to support new extension loading module in jupyterlab

### PR DESCRIPTION
**Pull request by Zsailer**
Hi @echarles,

Started working through your branches and adding just some minor changes that take advantage of the full features in jupyter_server's extension module.

I will likely need to do some clean up to get the tests passing...

### CODE REVIEW

**Comment by echarles** [comment]
Thx @Zsailer . CI is not run here. Could you try a local test with pytest?

**Comment by Zsailer** [comment]
Ok! I think this is ready for review. 

The biggest change is that I've removed the `extension.py` submodule in jupyterlab, because the LabApp itself *is* an extension.

**Comment by echarles** [comment]
Thx a lot @Zsailer for this! I have tested this branch locally and made 2 minor changes:

- Add in setup.py the nblcassic dep: `'nbclassic@ git+https://github.com/Zsailer/nbclassic@trait-shims'`
- Remove the usage of `load_jupyter_server_extension` in a test.

pytest is green, did also a few more sanity test : launch, build... Sound good so far.

I will merge this, fix the 2 bits and we will see what CI says.

**Comment by echarles** [comment]
@Zsailer We can iterate from here to fix the examples

When you run from `jupyterlab/examples/cell` the command` python main.py` it should open an working page. 

It returns an error `return self.settings[env].get_template(name) KeyError: 'lab_jinja2_env'`

**Pull request merged**
